name: watchlist_app
description: A new Flutter project.
publish_to: 'none' 


version: 3.0.0+3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.3
  http: ^0.13.5
  fade_shimmer: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:    
  android: 'launcher_icon'    
  ios: true    
  image_path: 'assets/logo.png'

flutter:

  uses-material-design: true
  assets:
    - assets/


